### ISSUE TITLE
Generate `hugo_stats.json` for PurgeCSS

### ISSUE THREAD

**Issue by salim-b** [gethyas/create-hyas#25]
Why don't we [let Hugo generate](https://gohugo.io/getting-started/configuration/#configure-build) all `class` attributes, `id` attributes, and tags actually in use in the built site via

```toml
[build.buildStats]
  enable = true
```

and use

```
 content: [ './hugo_stats.json' ],
```

instead of the current 

https://github.com/gethyas/create-hyas/blob/0c2051df0830969ad04679f73a6ad1e781f0bf32/template-doks/config/postcss.config.js#L9-L15

? 🙃

**Comment by h-enk** [comment]
That's absolutely way smarter!

**Comment by salim-b** [comment]
So let's do it! 🍻 https://github.com/gethyas/create-hyas/pull/27
