### ISSUE TITLE
Adpat `.Site-Params.seo` config for latest hyas/seo module

### ISSUE THREAD

**Issue by salim-b** [gethyas/create-hyas#29]
## Description

Config [for Doks](https://github.com/gethyas/create-hyas/blob/main/template-doks/config/_default/params.toml) and other templates that set up [Hyas' SEO module](https://github.com/gethyas/seo) is outdated and needs to be adapted to the [latest config schema](https://github.com/gethyas/seo/blob/main/config/_default/params.toml).

**Comment by h-enk** [comment]
Planned for — I will do this tomorrow

**Comment by h-enk** [comment]
👉 [v1.1.1](https://github.com/gethyas/create-hyas/releases/tag/v1.1.1)
